apiVersion: v1
kind: Secret
metadata: 
  name: mysecret-prod
  namespace: petclinic-prod
type: Opaque
data:
  ROOT_PASSWORD: cGV0Y2xpbmlj   #petclinic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic-prod
data:
  SQL_URL: "jdbc:mysql://mysql-headless-backend.petclinic-dev.svc.cluster.local:3306/petclinic"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-prod1
  namespace: petclinic-prod
type: Opaque
data:
  USER_NAME: cGV0Y2xpbmlj   #petclinic
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-prod2
  namespace: petclinic-prod
type: Opaque
data:
  USER_PASSWORD: cGV0Y2xpbmlj   #petclinic
