apiVersion: v1
kind: Secret
metadata: 
  name: mysecret-prod
  namespace: petclinic-prod
type: Opaque
data:
  ROOT_PASSWORD: cGV0Y2xpbmlj   #petclinic

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config-prod
  namespace: petclinic-prod
data:
  SQL_URL: "jdbc:mysql://mysql-headless-backend.petclinic-prod.svc.cluster.local:3306/petclinic"

