apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: petclinic-prod
  labels:
    app: petclinic-label-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-label-prod
  template:
    metadata:
      labels:
        app: petclinic-label-prod
    spec:
      serviceAccountName: petclinic-sa-prod
      containers:
      - name: petclinic-prod
        image: prasannakumarsinganamalla431/petclinic:10
        ports:
        - containerPort: 80
      env:
        - name: SQL_URL
          valueFrom:
            configMapKeyRef:
              name: petclinic-config-prod
              key: SQL_URL    


