apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-prod
  namespace: petclinic-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-sc
