apiVersion: v1
kind: ResourceQuota
metadata:
  name: petclinic-quota
  namespace: petclinic-prod
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10"
    services: "5"
    replicationcontrollers: "5"
    secrets: "10"
    configmaps: "10"

---

apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: petclinic-prod
spec:
  limits:
    - max:
        cpu: "2000m"
        memory: "2Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
