apiVersion: v1
kind: Service
metadata:
  name: frontend-service-prod
  namespace: petclinic-prod
spec:
  type: LoadBalancer
  selector:
    app: petclinic-label-prod
  ports:
    - port: 81
      targetPort: 80
