apiVersion: v1
kind: Service
metadata:
  name: frontend-service-prod
  namespace: petclinic-prod
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  selector:
    app: petclinic-label-prod
  ports:
    - port: 81
      targetPort: 80
