apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    []  
  mapUsers: |
    - userarn: arn:aws:iam::021891605639:user/kumar
      username: kumar
      groups:
        - Dev-admin
    - userarn: arn:aws:iam::021891605639:user/Murthy
      username: Murthy
      groups:
        - Prod-admin    
