apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-prod
  namespace: petclinic-prod
spec:
  podSelector: {}  # Applies to all pods in the petclinic-dev namespace
  policyTypes:
  - Ingress
  ingress:
  - from: []  # Deny all ingress traffic from the specified namespace
    namespaceSelector:
      matchLabels:
        name: petclinic-dev

# petclinic dev  will deny the ingress traffic from prod namespace (deny ingress from namespace which container lable as petclinic-prod) 

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-prod
  namespace: petclinic-dev
spec:
  podSelector: {}  # Applies to all pods in the petclinic-dev namespace
  policyTypes:
  - Ingress
  ingress:
  - from: []  # Deny all ingress traffic from the specified namespace
    namespaceSelector:
      matchLabels:
        name: petclinic-prod



         # petclinic prod will deny the ingress traffic from dev namespace (deny ingress from namespace which container lable as petclinic-dev) 
 