# In Kubernetes, when you want to control network traffic between namespaces, you should:

# # Allow Only the Necessary Traffic: Define NetworkPolicy rules that explicitly allow traffic only to the namespaces or pods that need to communicate with your prod namespace.

# # Implicit Denial: Any traffic that is not explicitly allowed by your NetworkPolicy will be implicitly denied. This means that if you don’t create a rule to allow communication with certain namespaces (like dev), that communication will automatically be restricted.
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: deny-ALL
#   namespace: petclinic-prod
# spec:
#   podSelector: {}  # This applies to all pods in the petclinic-prod namespace
#   policyTypes:
#   - Ingress
#   - Egress
  


# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: deny-ALL
#   namespace: petclinic-dev
# spec:
#   podSelector: {}  # This applies to all pods in the petclinic-dev namespace
#   policyTypes:
#   - Ingress
#   - Egress

#  # no traffic will be allowed into the pods in that namespace by default.
#  # no traffic will be allowed out of the pods in that namespace by default.  not even just between the dev and prod but also with every namespace present in the cluster 
# #--------------------------------------------------------------------------------
# ---
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-traffic-within-prod-namespace
#   namespace: petclinic-prod
# spec:
#   podSelector: 
#    matchLabels:
#     ns: pet-prod
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels:
#           ns: prod
#   egress:
#   - to:
#     - podSelector:
#         matchLabels:
#           ns: pet-prod


#           #Even though Kubernetes allows all intra-namespace traffic by default, this policy can be used to explicitly define and document which pods are allowed to communicate within the namespace, adding an extra layer of clarity and control.
#           #only pods with label ns:pet-prod can communicate with eachother in prod namespace as per the given rule

---
#-----------------------------------------------------------------------------

# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: allow-traffic-from-dev-to-prod----and-send-only-to-dev
#   namespace: petclinic-prod
# spec:
#   podSelector: 
#   policyTypes:
#   - Ingress
#   - Egress
#   ingress:
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           namespace: petclinic-dev
#   egress:
#   - to:
#     - namespaceSelector:
#         matchLabels:
#           namespace: petclinic-dev    

        #the petclinic-prod namespace will only allow traffic from the petclinic-dev namespace and will only send traffic to the petclinic-dev namespace.      
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-communication-from-specific-namespaces
  namespace: petclinic-dev
spec:
  podSelector: {}  # Applies to all Pods in petclinic-dev
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: prometheus
    - namespaceSelector:
        matchLabels:
          name: grafana
    - namespaceSelector:
        matchLabels:
          name: argocd
    - namespaceSelector:
        matchLabels:
          name: ingress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: prometheus
    - namespaceSelector:
        matchLabels:
          name: grafana
    - namespaceSelector:
        matchLabels:
          name: argocd
    - namespaceSelector:
        matchLabels:
          name: ingress
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-communication-from-specific-namespaces
  namespace: petclinic-prod
spec:
  podSelector: {}  # Applies to all Pods in petclinic-prod
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: prometheus
    - namespaceSelector:
        matchLabels:
          name: grafana
    - namespaceSelector:
        matchLabels:
          name: argocd
    - namespaceSelector:
        matchLabels:
          name: ingress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    - namespaceSelector:
        matchLabels:
          name: prometheus
    - namespaceSelector:
        matchLabels:
          name: grafana
    - namespaceSelector:
        matchLabels:
          name: argocd
    - namespaceSelector:
        matchLabels:
          name: ingress

