apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
reclaimPolicy: retain
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
parameters:
  type: gp2
allowVolumeExpansion: true


