apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-backend
  namespace: petclinic-dev
  annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"   
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306