apiVersion: v1
kind: Secret
metadata: 
  name: mysecret-dev
  namespace: petclinic-dev
type: Opaque
data:
  ROOT_PASSWORD: cGV0Y2xpbmlj   #petclinic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic-dev
data:
  SQL_URL: "jdbc:mysql://mysql-headless-backend.petclinic-prod.svc.cluster.local:3306/petclinic"