apiVersion: v1
kind: Secret
metadata: 
  name: mysecret-dev
  namespace: petclinic-dev
type: Opaque
data:
  ROOT_PASSWORD: cGV0Y2xpbmlj   #petclinic

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config-dev
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS Petdata;
    USE Petdata;

    CREATE TABLE Petdata (
    Name VARCHAR(100) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Address VARCHAR(255) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Telephone VARCHAR(15),
    pets VARCHAR(255));