apiVersion: v1
kind: Secret
metadata: 
  name: mysecret-dev 
  namespace: petclinic-dev
type: Opaque
data:
  ROOT_PASSWORD: cGV0Y2xpbmlj   #petclinic
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic-dev
data:
  MYSQL_URL: "jdbc:mysql://mysql-headless-backend.petclinic-dev.svc.cluster.local:3306/petclinic"

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-dev1
  namespace: petclinic-dev
type: Opaque
data:
  MYSQL_USER: cGV0Y2xpbmlj   #petclinic
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-dev2
  namespace: petclinic-dev
type: Opaque
data:
  MYSQL_PASSWORD: cGV0Y2xpbmlj   #petclinic
