apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  namespace: petclinic-dev
  labels:
    app: petclinic-label-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic-label-dev
  template:
    metadata:
      labels:
        app: petclinic-label-dev
    spec:
      serviceAccountName: petclinic-sa-dev
      containers:
      - name: petclinic-dev
        image: prasannakumarsinganamalla431/petclinic:10
        ports:
        - containerPort: 80
      env:
        - name: SQL_URL
          valueFrom:
            configMapKeyRef:
              name: petclinic-config
              key: SQL_URL

