apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-petclinic-dev
  namespace: petclinic-prod
spec:
  type: LoadBalancer
  rules:
  - host: "www.petclinic.com"
    http:
      paths:
      - pathType: Prefix
        path: "/dev"
        backend:
          service:
            name: frontend-service-dev
            port:
              number: 80