apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dev-claim
  namespace: petclinic-dev
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: ebs-sc
