apiVersion: v1
kind: ResourceQuota
metadata:
  name: petclinic-quota
  namespace: petclinic-dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "3Gi"
    limits.cpu: "2"
    limits.memory: "6Gi"
    pods: "8"
    services: "4"
    replicationcontrollers: "5"
    secrets: "10"
    configmaps: "10"
