apiVersion: v1
kind: Service
metadata:
  name: frontend-service-dev
  namespace: petclinic-dev
  annotations:
    Prometheus.io/path: /actuator/Prometheus
    Prometheus.io/scrape: "true"  
spec:
  type: LoadBalancer
  selector:
    app: petclinic-label-dev
  ports:
    - port: 81
      targetPort: 80
