apiVersion: v1
kind: Service
metadata:
  name: frontend-service-dev
  namespace: petclinic-dev
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/scrape: "true"
    prometheus.io/port: '81'
spec:
  type: LoadBalancer
  selector:
    app: petclinic-label-dev
  ports:
    - port: 81
      targetPort: 80