apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: petclinic-dev
spec:
  serviceName: "mysql-headless-backend"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: petclinic-sa-dev
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: ROOT_PASSWORD
                  name: mysecret-dev
          volumeMounts:
            - name: mysql-storage-dev
              mountPath: /var/lib/mysql
    volumes:
      - name: mysql-storage-dev
        configMap:
          name: mysql-initdb-config-dev         
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage-dev
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: ebs-sc
